services:
  app:
    container_name: nest-api 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    depends_on:
      - postgres
    networks:
      - postgres_network
    volumes:
      - app_logs:/app/logs

  postgres:
    container_name: mydb 
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
    name: postgres_data
  app_logs:
    name: app_logs
